name: tps
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - basemap
  - pygrib
  - lxml 
  - pymongo
  - pip
  - pip:
    - pymongo[srv]
#*  conda env create --file environment.yml
#*  conda env update --file environment.yml --prune