name: production-env
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - matplotlib
  - basemap
  # required for MMM-py degribing
  - pygrib
  # lxml is used for webscraping
  - lxml 
  # pymongo is the connection to mongodb
  - pymongo 
